LC-362 Changed how validate connection works for HTTPSolrClient versus CloudSolrClient
kmwtechnology/lucille pull request #48
Opened 2023-09-21 19:57 UTC by abijitran

Saw issues with HTTPSolrClient not correctly being validated, changed it so that it is now using a .ping() for httpclient and the old method for the Cloud client.

2023-09-26 18:59 UTC, rseitz commented on lucille-core/src/main/java/com/kmwllc/lucille/indexer/SolrIndexer.java
> +          log.error("Non zero response when checking solr cluster status: " + status);
update error message to talk about pinging rather than checking cluster status

2023-09-26 19:03 UTC, rseitz requested changes
realized we need test coverage for both scenarios...
ideally the test would create a mock solr client of each type
create a SolrIndexer using the constructor that lets us pass in a solr client
then call validateConnection on the solr client
finally check that right method was called on the mock client

2023-09-26 19:28 UTC, kyle-kmw commented
I noticed some existing tests are failing on this branch.

2023-09-21T20:01:29.9832230Z [ERROR] Errors: 
2023-09-21T20:01:29.9833750Z [ERROR]   RunnerTest.testIndexerConnectFailure:738 » IllegalArgument port out of range:1...
2023-09-21T20:01:29.9834500Z [ERROR]   SolrIndexerIntegrationTest.testDeleteByField:168 » RemoteSolr Error from serve...
2023-09-21T20:01:29.9835110Z [ERROR]   SolrIndexerIntegrationTest.testDeleteById:98 » RemoteSolr Error from server at...
2023-09-21T20:01:29.9835720Z [ERROR]   SolrIndexerIntegrationTest.testDeleteByIdsAndFields:246 » RemoteSolr Error fro...

> realized we need test coverage for both scenarios... ideally the test would create a mock solr client of each type create a SolrIndexer using the constructor that lets us pass in a solr client then call validateConnection on the solr client finally check that right method was called on the mock client

I agree with extending test coverage but I think the test will be more resilient if we write solr teste framework tests (embedded solr) instead of client mocks.

2023-10-16 19:53 UTC, abijitran commented
```suggestion
ttest
```

2023-10-16 19:53 UTC, closed without merging