Bugfix/lc 263 csvconnector error handling
kmwtechnology/lucille pull request #61
Opened 2023-10-31 19:49 UTC by h0rban

2023-10-31 19:55 UTC, rseitz commented on lucille-core/src/main/java/com/kmwllc/lucille/connector/CSVConnector.java
> +    if(lineNum != 0) {
please add a space after the "if"

2023-10-31 20:42 UTC, rseitz approved these changes
Approving but would like to kyle to review as well before we merge

2023-11-01 01:08 UTC, kyle-kmw approved these changes

2023-11-01 13:36 UTC, rseitz requested changes
After an initial parsing error, the reported line numbers of further errors are not always accurate.

If the test csv is extended like this:

a,b,c
1,2,3
4,5
6,7,8
9,10,11
"{}",12,"
",13,14
",hi,hello
a,b,c"
15,16,17
18,19,20
21,22
23,24
25,26,27

The output is:

23/11/01 09:32:22 WARN CSVConnector: Line 3 of the csv has a different number of columns than columns in the header.
23/11/01 09:32:22 WARN CSVConnector: Line 6 of the csv has a different number of columns than columns in the header.
23/11/01 09:32:22 WARN CSVConnector: Line 7 of the csv has a different number of columns than columns in the header.
23/11/01 09:32:22 WARN CSVConnector: Line 10 of the csv has a different number of columns than columns in the header.
23/11/01 09:32:22 WARN CSVConnector: Line 11 of the csv has a different number of columns than columns in the header.

2023-11-01 17:04 UTC, rseitz commented
Closing this PR in favor of https://github.com/kmwtechnology/lucille/pull/63

2023-11-01 17:04 UTC, closed without merging